apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book
          image: registry.gitlab.com/ripitchip/418-teapot:1.0.2
          ports:
            - containerPort: 80
